services:
	api:
		build: 
			context: .
			dockerfile: Dockerfile
		ports:
			- '3000:3000'
		depends_on:
			- 'mysql_db'
		environment:
			DATABASE_TYPE: ${DATABASE_TYPE}
			DATABASE_HOST: ${DATABASE_HOST}
			DATABASE_PORT: ${DATABASE_PORT}
			DATABASE_USER: ${DATABASE_USER}
			DATABASE_PASS: ${DATABASE_PASS}
			DATABASE_NAME: ${DATABASE_NAME}
			JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
			JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
			JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
			PASSWORD_HASH_SALT: ${PASSWORD_HASH_SALT}
	mysql_db:
		image: mysql
		restart: always
		ports:
			- '${DATABASE_PORT}:${DATABASE_PORT}'
		environment:
			MYSQL_TCP_PORT: ${DATABASE_PORT}
			MYSQL_DATABASE: ${DATABASE_NAME}
			MYSQL_USER: ${DATABASE_USER}
			MYSQL_PASSWORD: ${DATABASE_PASS}
			MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
